assign:
  strategy:
    random
    # round-robin
  schedule:
    '*/1 * * * *'
  assignees:
    - break2017
#     - ZwwWayne
#     - jshilong
#     - hhaAndroid
#     - AronLin
#     - RangiLyu
#     - BIGWangYuDong
